# file      : tests/basic/buildfile
# license   : BSD 2-Clause "Simplified" License; see accompanying COPYING file

import libs  = libcmark-gfm-extensions%lib{cmark-gfm-extensions}
import libs += libcmark-gfm%lib{cmark-gfm}

exe{driver}: {h c}{**} $libs testscript
